# Generated by Django 3.2.18 on 2023-05-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tundorul', '0016_delete_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='tundorul.userprofile')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_suggestions', to='tundorul.UserProfile')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
