# Generated by Django 3.2.18 on 2023-03-20 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField()),
                ('time_watched', models.TimeField()),
                ('channel_points', models.IntegerField()),
                ('is_subscribed', models.BooleanField()),
                ('subscribed_since', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'Published')], default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
    ]
