# Generated by Django 3.2.18 on 2023-05-15 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('url', models.CharField(max_length=255)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=200)),
                ('current_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_follower', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
    ]
