# Generated by Django 3.2.18 on 2023-05-15 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tundorul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vods',
            name='stream_id',
            field=models.CharField(default=0, max_length=255),
        )
    ]
