# Generated by Django 3.2.18 on 2023-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocial',
            name='last_login',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
