# Generated by Django 3.2.18 on 2023-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0002_auto_20230515_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.TextField(blank=True),
        ),
    ]
