# Generated by Django 3.2.18 on 2023-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0002_auto_20230410_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSchedule',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(blank=True)),
                ('timezone', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('is_recuring', models.BooleanField()),
                ('category_id', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
