# Generated by Django 3.2.18 on 2023-04-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0003_streamschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamschedule',
            name='day',
            field=models.TextField(default='Monday'),
        ),
    ]
