# Generated by Django 3.2.18 on 2023-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0004_alter_vods_stream_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('author', models.TextField()),
                ('author_profile_img', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('votes', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
