# Generated by Django 3.2.18 on 2023-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0004_streamschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamschedule',
            name='day',
            field=models.CharField(default='Monday', max_length=200),
        ),
    ]
