# Generated by Django 3.2.18 on 2023-04-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0005_alter_streamschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamschedule',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
