# Generated by Django 3.2.18 on 2023-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0005_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vods',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
