# Generated by Django 3.2.18 on 2023-04-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0006_alter_streamschedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamschedule',
            name='timezone',
            field=models.CharField(default='UK/LONDON', max_length=200),
        ),
    ]
