# Generated by Django 3.2.18 on 2023-05-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0007_auto_20230516_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
