# Generated by Django 3.2.18 on 2023-04-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0007_alter_streamschedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamschedule',
            name='twitch_segment_id',
            field=models.CharField(default='new', max_length=200),
        ),
        migrations.AlterField(
            model_name='streamschedule',
            name='category_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
