# Generated by Django 3.2.18 on 2023-04-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0008_auto_20230414_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamschedule',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='streamschedule',
            name='segment_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='streamschedule',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
