# Generated by Django 3.2.18 on 2023-05-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0008_suggestions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
