# Generated by Django 3.2.18 on 2023-04-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0009_auto_20230419_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamschedule',
            old_name='is_recuring',
            new_name='is_recurring',
        ),
    ]
