# Generated by Django 3.2.18 on 2023-04-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0010_rename_is_recuring_streamschedule_is_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamschedule',
            name='twitch_segment_id',
        ),
    ]
