# Generated by Django 3.2.18 on 2023-05-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0010_auto_20230517_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
