# Generated by Django 3.2.18 on 2023-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0013_auto_20230518_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='user_profile',
            new_name='author',
        ),

    ]
