# Generated by Django 3.2.18 on 2023-04-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0013_alter_streamschedule_timezone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamSchedule',
        ),
    ]
