# Generated by Django 3.2.18 on 2023-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0014_delete_streamschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_watched',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
