# Generated by Django 3.2.18 on 2023-05-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0015_alter_userprofile_join_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
