# Generated by Django 3.2.18 on 2023-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0016_delete_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vods',
            name='published_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
