# Generated by Django 3.2.18 on 2023-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0017_remove_userprofile_following_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
