# Generated by Django 3.2.18 on 2023-10-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tundorul', '0017_alter_vods_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
