# Generated by Django 3.2.18 on 2023-05-09 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0018_auto_20230509_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
