# Generated by Django 3.2.18 on 2023-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0019_userprofile_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
