# Generated by Django 3.2.18 on 2023-05-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tundorul', '0021_alter_userprofile_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='channel_points',
        ),
    ]
